.TH INTERNSCTL 1 "January 2024" "v0.1.0" "internsctl manual"
.SH NAME
internsctl \- custom Linux command for operations

.SH SYNOPSIS
.B internsctl
[\fIOPTION\fR]...

.SH DESCRIPTION
This is a custom Linux command designed for various operations.

.SH OPTIONS
.TP
.B \-\-help
Display help information.

.TP
.B \-\-version
Display the command version.

.TP
.B cpu getinfo
Get CPU information similar to lscpu command.

.TP
.B memory getinfo
Get memory information similar to free command.

